# Generated by Django 4.2.11 on 2024-06-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpd_mnth_id", models.CharField(max_length=100)),
                ("cpd_dt", models.DateField()),
                ("cluster_name_adjusted", models.CharField(max_length=100)),
                ("mrch_catg_cd", models.CharField(max_length=10)),
                ("mrch_catg_rlup_nm", models.CharField(max_length=100)),
                ("merchant", models.CharField(max_length=100)),
                ("cp_flag", models.BooleanField()),
                ("domestic_flag", models.BooleanField()),
                ("intraregion_flag", models.BooleanField()),
                ("interregion_flag", models.BooleanField()),
                ("city_name", models.CharField(blank=True, max_length=100, null=True)),
                ("country_code", models.CharField(max_length=10)),
                ("spend", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
